### ISSUE TITLE
An error occurred while running the interactive demo, how to solve it

### ISSUE THREAD

**Issue by wang-shuaikang** [SysCV/sam-pt#13]
(sam) D:\computer_vision\sam-pt>python -m demo.demo frames_path='sam-pt/data/demo_data/demo/' query_points_path=null longest_side_length=1024 frame_stride=1 max_frames=-1
E:\Anaconda3\envs\sam\lib\site-packages\hydra\_internal\hydra.py:119: UserWarning: Future Hydra versions will no longer change working directory at job runtime by default.
See https://hydra.cc/docs/1.2/upgrades/1.1_to_1.2/changes_to_job_working_dir/ for more information.
  ret = run_job(
Setting seed to 72
model:
  point_tracker:
    _target_: sam_pt.point_tracker.pips.PipsPointTracker
    checkpoint_path: ${hydra:runtime.cwd}/models/pips_ckpts/reference_model
    stride: 4
    s: 8
    initial_next_frame_visibility_threshold: 0.9
  sam_predictor:
    sam_model:
      image_encoder:
        _target_: segment_anything.modeling.image_encoder.ImageEncoderViT
        depth: 32
        embed_dim: 1280
        img_size: ${ ..image_size }
        mlp_ratio: 4
        norm_layer:
          _partial_: true
          _target_: torch.nn.LayerNorm
          eps: 1.0e-06
        num_heads: 16
        patch_size: ${ ..vit_patch_size }
        qkv_bias: true
        use_rel_pos: true
        global_attn_indexes:
        - 7
        - 15
        - 23
        - 31
        window_size: 14
        out_chans: ${ ..prompt_embed_dim }
      prompt_encoder:
        _target_: segment_anything.modeling.prompt_encoder.PromptEncoder
        embed_dim: ${ ..prompt_embed_dim }
        image_embedding_size:
        - ${ ...image_embedding_size }
        - ${ ...image_embedding_size }
        input_image_size:
        - ${ ...image_size }
        - ${ ...image_size }
        mask_in_chans: 16
      mask_decoder:
        _target_: segment_anything.modeling.mask_decoder.MaskDecoder
        num_multimask_outputs: 3
        transformer:
          _target_: segment_anything.modeling.transformer.TwoWayTransformer
          depth: 2
          embedding_dim: ${ ...prompt_embed_dim }
          mlp_dim: 2048
          num_heads: 8
        transformer_dim: ${ ..prompt_embed_dim }
        iou_head_depth: 3
        iou_head_hidden_dim: 256
      _target_: sam_pt.modeling.sam.SamHydra
      checkpoint: ${hydra:runtime.cwd}/models/sam_ckpts/sam_vit_h_4b8939.pth
      prompt_embed_dim: 256
      image_size: 1024
      vit_patch_size: 16
      image_embedding_size: 64
      pixel_mean:
      - 123.675
      - 116.28
      - 103.53
      pixel_std:
      - 58.395
      - 57.12
      - 57.375
    _target_: segment_anything.predictor.SamPredictor
  _target_: sam_pt.modeling.sam_pt.SamPt
  sam_iou_threshold: 0.7
  iterative_refinement_iterations: 12
  positive_point_selection_method: kmedoids
  negative_point_selection_method: mixed
  positive_points_per_mask: -1
  negative_points_per_mask: -1
  add_other_objects_positive_points_as_negative_points: true
  point_tracker_mask_batch_size: 5
  use_patch_matching_filtering: false
  patch_size: 3
  patch_similarity_threshold: 0.01
  use_point_reinit: false
  reinit_point_tracker_horizon: 8
  reinit_horizon: 8
  reinit_variant: reinit-on-horizon-and-sync-masks
logging:
  wandb:
    entity: null
    project: demo
    tensorboard: true
    log_code_path: ${hydra:runtime.cwd}/sam_pt
  debug: false
  exp_id: debug_72_2023.08.12_14.24.36
frames_path: sam-pt/data/demo_data/demo/
query_points_path: null
longest_side_length: 1024
frame_stride: 1
max_frames: -1
seed: 72
annot_size: 16
annot_line_width: 6

wandb: W&B API key is configured. Use `wandb login --relogin` to force relogin
wandb: Network error (SSLError), entering retry loop.
wandb: Network error (SSLError), entering retry loop.
[2023-08-12 14:25:45,470][urllib3.connectionpool][WARNING] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLZero
ReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1131)'))': /api/4504800232407040/store/
[2023-08-12 14:25:46,266][urllib3.connectionpool][WARNING] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLZero
ReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1131)'))': /api/4504800232407040/store/
Problem at: D:\computer_vision\sam-pt\demo\demo.py 75 setup_logging
Error executing job with overrides: ["frames_path='sam-pt/data/demo_data/demo/'", 'query_points_path=null', 'longest_side_length=1024', 'frame_stride=1', 'max_frames=-1']
wandb: ERROR Run initialization has timed out after 60.0 sec.
wandb: ERROR Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-       
Traceback (most recent call last):
  File "E:\Anaconda3\envs\sam\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "E:\Anaconda3\envs\sam\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\computer_vision\sam-pt\demo\demo.py", line 372, in <module>
    main()
  File "E:\Anaconda3\envs\sam\lib\site-packages\hydra\main.py", line 94, in decorated_main
    _run_hydra(
  File "E:\Anaconda3\envs\sam\lib\site-packages\hydra\_internal\utils.py", line 394, in _run_hydra
    _run_app(
  File "E:\Anaconda3\envs\sam\lib\site-packages\hydra\_internal\utils.py", line 457, in _run_app
    run_and_report(
  File "E:\Anaconda3\envs\sam\lib\site-packages\hydra\_internal\utils.py", line 223, in run_and_report
    raise ex
  File "E:\Anaconda3\envs\sam\lib\site-packages\hydra\_internal\utils.py", line 220, in run_and_report
    return func()
  File "E:\Anaconda3\envs\sam\lib\site-packages\hydra\_internal\utils.py", line 458, in <lambda>
    lambda: hydra.run(
  File "E:\Anaconda3\envs\sam\lib\site-packages\hydra\_internal\hydra.py", line 132, in run
    _ = ret.return_value
  File "E:\Anaconda3\envs\sam\lib\site-packages\hydra\core\utils.py", line 260, in return_value
    raise self._return_value
  File "E:\Anaconda3\envs\sam\lib\site-packages\hydra\core\utils.py", line 186, in run_job
    ret.return_value = task_function(task_cfg)
  File "D:\computer_vision\sam-pt\demo\demo.py", line 42, in main
    setup_logging(cfg)
  File "D:\computer_vision\sam-pt\demo\demo.py", line 75, in setup_logging
    wandb.init(
  File "E:\Anaconda3\envs\sam\lib\site-packages\wandb\sdk\wandb_init.py", line 1169, in init
    raise e
  File "E:\Anaconda3\envs\sam\lib\site-packages\wandb\sdk\wandb_init.py", line 1150, in init
    run = wi.init()
  File "E:\Anaconda3\envs\sam\lib\site-packages\wandb\sdk\wandb_init.py", line 769, in init
    raise error
wandb.errors.CommError: Run initialization has timed out after 60.0 sec.
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
[2023-08-12 14:25:47,013][urllib3.connectionpool][WARNING] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLZero
ReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1131)'))': /api/4504800232407040/store/
[2023-08-12 14:25:48,531][urllib3.connectionpool][WARNING] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLZero
ReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1131)'))': /api/4504800232407040/envelope/
[2023-08-12 14:25:49,424][urllib3.connectionpool][WARNING] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLZero
ReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1131)'))': /api/4504800232407040/envelope/
[2023-08-12 14:25:50,050][urllib3.connectionpool][WARNING] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLZero
ReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1131)'))': /api/4504800232407040/envelope/

**Comment by wang-shuaikang** [comment]
This is because I use it as a proxy VPN, just turn off the VPN

**Comment by m43** [comment]
Hej, happy you resolved your issue, closing it now
