### ISSUE TITLE
Error running the Non-interactivte Demo

### ISSUE THREAD

**Issue by Micro-han** [SysCV/sam-pt#31]
Thanks for your great work, but I meet some errors when I running the demo. I tried to change the PYTHONPATH and check the __init__.py files, but I still have no idea about how to solve it.

```
Error executing job with overrides: ['frames_path=${hydra:runtime.cwd}/data/demo_data/bees/', 'query_points_path=${hydra:runtime.cwd}/data/demo_data/query_points__bees.txt', 'longest_side_length=1024', 'frame_stride=1', 'max_frames=-1', 'model.use_point_reinit=true']
Traceback (most recent call last):
  File "/conda/envs/sampt/lib/python3.8/site-packages/hydra/_internal/utils.py", line 644, in _locate
    obj = getattr(obj, part)
AttributeError: module 'sam_pt.modeling' has no attribute 'sam_pt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/conda/envs/sampt/lib/python3.8/site-packages/hydra/_internal/utils.py", line 650, in _locate
    obj = import_module(mod)
  File "/conda/envs/sampt/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/sam-pt/sam_pt/modeling/sam_pt.py", line 15, in <module>
    from sam_pt.point_tracker import PointTracker, SuperGluePointTracker
  File "/sam-pt/sam_pt/point_tracker/__init__.py", line 7, in <module>
    from .cotracker import CoTrackerPointTracker
  File "/sam-pt/sam_pt/point_tracker/cotracker/__init__.py", line 1, in <module>
    from .tracker import CoTrackerPointTracker
  File "/sam-pt/sam_pt/point_tracker/cotracker/tracker.py", line 6, in <module>
    from cotracker.models.core.cotracker.cotracker import CoTracker
ImportError: cannot import name 'CoTracker' from 'cotracker.models.core.cotracker.cotracker' (/sam-pt/co-tracker/cotracker/models/core/cotracker/cotracker.py)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/conda/envs/sampt/lib/python3.8/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 134, in _resolve_target
    target = _locate(target)
  File "/conda/envs/sampt/lib/python3.8/site-packages/hydra/_internal/utils.py", line 658, in _locate
    raise ImportError(
ImportError: Error loading 'sam_pt.modeling.sam_pt.SamPt':
ImportError("cannot import name 'CoTracker' from 'cotracker.models.core.cotracker.cotracker' (/sam-pt/co-tracker/cotracker/models/core/cotracker/cotracker.py)")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/conda/envs/sampt/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/conda/envs/sampt/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/sam-pt/demo/demo.py", line 371, in <module>
    main()
  File "/conda/envs/sampt/lib/python3.8/site-packages/hydra/main.py", line 94, in decorated_main
    _run_hydra(
  File "/conda/envs/sampt/lib/python3.8/site-packages/hydra/_internal/utils.py", line 394, in _run_hydra
    _run_app(
  File "/conda/envs/sampt/lib/python3.8/site-packages/hydra/_internal/utils.py", line 457, in _run_app
    run_and_report(
  File "/conda/envs/sampt/lib/python3.8/site-packages/hydra/_internal/utils.py", line 223, in run_and_report
    raise ex
  File "/conda/envs/sampt/lib/python3.8/site-packages/hydra/_internal/utils.py", line 220, in run_and_report
    return func()
  File "/conda/envs/sampt/lib/python3.8/site-packages/hydra/_internal/utils.py", line 458, in <lambda>
    lambda: hydra.run(
  File "/conda/envs/sampt/lib/python3.8/site-packages/hydra/_internal/hydra.py", line 132, in run
    _ = ret.return_value
  File "/conda/envs/sampt/lib/python3.8/site-packages/hydra/core/utils.py", line 260, in return_value
    raise self._return_value
  File "/conda/envs/sampt/lib/python3.8/site-packages/hydra/core/utils.py", line 186, in run_job
    ret.return_value = task_function(task_cfg)
  File "/sam-pt/demo/demo.py", line 49, in main
    model = load_model(cfg, positive_points_per_mask, negative_points_per_mask)
  File "/sam-pt/demo/demo.py", line 109, in load_model
    model = instantiate(cfg.model)
  File "/conda/envs/sampt/lib/python3.8/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 226, in instantiate
    return instantiate_node(
  File "/conda/envs/sampt/lib/python3.8/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 333, in instantiate_node
    _target_ = _resolve_target(node.get(_Keys.TARGET), full_key)
  File "/conda/envs/sampt/lib/python3.8/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 139, in _resolve_target
    raise InstantiationException(msg) from e
hydra.errors.InstantiationException: Error locating target 'sam_pt.modeling.sam_pt.SamPt', set env var HYDRA_FULL_ERROR=1 to see chained exception.
full_key: model
```

**Comment by Micro-han** [comment]
Sorry for troublesome, I installed mismatched version of `co-tacker`, and this issue should be closed.
